In [2]:
from systemml import dml, MLContext
import numpy as np

ml= MLContext(spark)

script ="""
c= sum( a %*% t(b)) 
"""

a= np.array([[1,2,3]])
b= np.array([[4,5,6]])
prog= dml(script).input('a',a).input('b',b).output('c')
c=ml.execute(prog).get('c')

NameError: name 'spark' is not defined

In [20]:
import numpy as np

x = np.array([[[1],[2],[3]], [[4],[5],[6]], [[7],[8],[9]], [[10],[11],[12]]])
#x = np.array([[[1],[2],[3]], [[4],[5],[6]]], )


In [21]:
x[1]

array([[4],
       [5],
       [6]])

In [28]:
x[:,[0:2:1]]

SyntaxError: invalid syntax (<ipython-input-28-ef3c0456410f>, line 1)

In [29]:
x[:,-1]

array([[ 3],
       [ 6],
       [ 9],
       [12]])

In [30]:
x[:,:-1]

array([[[ 1],
        [ 2]],

       [[ 4],
        [ 5]],

       [[ 7],
        [ 8]],

       [[10],
        [11]]])